// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUxPsOhlHMUSFIYlayMI13SuYrczMNobg',
    appId: '1:1062111789785:web:4ef3c03ef7e9f2f6b874c8',
    messagingSenderId: '1062111789785',
    projectId: 'deardiary120-b5be9',
    authDomain: 'deardiary120-b5be9.firebaseapp.com',
    databaseURL: 'https://deardiary120-b5be9-default-rtdb.firebaseio.com',
    storageBucket: 'deardiary120-b5be9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-LcatNKn760m0ELD0RUHx-XH8qLAF_c',
    appId: '1:1062111789785:android:2011f32832f9b8c0b874c8',
    messagingSenderId: '1062111789785',
    projectId: 'deardiary120-b5be9',
    databaseURL: 'https://deardiary120-b5be9-default-rtdb.firebaseio.com',
    storageBucket: 'deardiary120-b5be9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZOoG-6kjveLrzcvnPGOT78dZq-2UzVNQ',
    appId: '1:1062111789785:ios:c4bb9812c428b6e7b874c8',
    messagingSenderId: '1062111789785',
    projectId: 'deardiary120-b5be9',
    databaseURL: 'https://deardiary120-b5be9-default-rtdb.firebaseio.com',
    storageBucket: 'deardiary120-b5be9.appspot.com',
    iosClientId: '1062111789785-3hl3ai6sdh7plhhi61t31ro1kvfg6dt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZOoG-6kjveLrzcvnPGOT78dZq-2UzVNQ',
    appId: '1:1062111789785:ios:d5097da988ebe1c7b874c8',
    messagingSenderId: '1062111789785',
    projectId: 'deardiary120-b5be9',
    databaseURL: 'https://deardiary120-b5be9-default-rtdb.firebaseio.com',
    storageBucket: 'deardiary120-b5be9.appspot.com',
    iosClientId: '1062111789785-c4ah298s3uhsvth93ubim2onk3tnj5cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryProject.RunnerTests',
  );
}
